In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from pathlib import Path
from tqdm.auto import tqdm
from itertools import cycle

pio.templates.default = "plotly_white"

np.random.seed()
tqdm.pandas()

In [2]:
SAVE_FIGURES = False
if SAVE_FIGURES:
    os.makedirs('imgs/chapter_2', exist_ok=True)

In [3]:
df = pd.read_excel("https://archive.ics.uci.edu/ml/machine-learning-databases/00247/data_akbilgic.xlsx", skiprows=1)

df.head()

C:\Users\David\PycharmProjects\Modern-Time-Series-Forecasting-with-Python-2E\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:332: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,date,ISE,ISE.1,SP,DAX,FTSE,NIKKEI,BOVESPA,EU,EM
0,2009-01-05,0.035754,0.038376,-0.004679,0.002193,0.003894,0.000000,0.031190,0.012698,0.028524
1,2009-01-06,0.025426,0.031813,0.007787,0.008455,0.012866,0.004162,0.018920,0.011341,0.008773
2,2009-01-07,-0.028862,-0.026353,-0.030469,-0.017833,-0.028735,0.017293,-0.035899,-0.017073,-0.020015
3,2009-01-08,-0.062208,-0.084716,0.003391,-0.011726,-0.000466,-0.040061,0.028283,-0.005561,-0.019424
4,2009-01-09,0.009860,0.009658,-0.021533,-0.019873,-0.012710,-0.004474,-0.009764,-0.010989,-0.007802

In [4]:
pd.to_datetime("13-4-1987").strftime('%d, %B %Y')

C:\Users\David\AppData\Local\Temp\ipykernel_99212\1410252913.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.to_datetime("13-4-1987").strftime('%d, %B %Y')

'13, April 1987'

In [5]:
pd.to_datetime('4-1-1987').strftime('%d, %B %Y')

'01, April 1987'

In [6]:
pd.to_datetime('4-1-1987', dayfirst=True).strftime('%d, %B %Y')

'04, January 1987'

In [7]:
pd.to_datetime('4|1|1987', format='%d|%m|%Y').strftime('%d, %B %Y')

'04, January 1987'

In [8]:
df['date'] = pd.to_datetime(df['date'], yearfirst=True)
df['date'].dtype

dtype('<M8[ns]')

In [9]:
df['date'].min(), df['date'].max()

(Timestamp('2009-01-05 00:00:00'), Timestamp('2011-02-22 00:00:00'))

In [10]:
df.head()

,date,ISE,ISE.1,SP,DAX,FTSE,NIKKEI,BOVESPA,EU,EM
0,2009-01-05,0.035754,0.038376,-0.004679,0.002193,0.003894,0.000000,0.031190,0.012698,0.028524
1,2009-01-06,0.025426,0.031813,0.007787,0.008455,0.012866,0.004162,0.018920,0.011341,0.008773
2,2009-01-07,-0.028862,-0.026353,-0.030469,-0.017833,-0.028735,0.017293,-0.035899,-0.017073,-0.020015
3,2009-01-08,-0.062208,-0.084716,0.003391,-0.011726,-0.000466,-0.040061,0.028283,-0.005561,-0.019424
4,2009-01-09,0.009860,0.009658,-0.021533,-0.019873,-0.012710,-0.004474,-0.009764,-0.010989,-0.007802

In [11]:
print(f"""
Date: {df['date'].iloc[0]}
Day of year: {df['date'].dt.day_of_year.iloc[0]}
Day of week: {df['date'].dt.dayofweek.iloc[0]}
Month: {df['date'].dt.month.iloc[0]}
Month Name: {df['date'].dt.month_name().iloc[0]}
Quarter: {df['date'].dt.quarter.iloc[0]}
Year: {df['date'].dt.year.iloc[0]}
ISO Week: {df['date'].dt.isocalendar().week.iloc[0]}
""")

Date: 2009-01-05 00:00:00
Day of year: 5
Day of week: 0
Month: 1
Month Name: January
Quarter: 1
Year: 2009
ISO Week: 2

In [12]:
df.set_index('date', inplace=True)

In [13]:
df['2010-01-04':]

,ISE,ISE.1,SP,DAX,FTSE,NIKKEI,BOVESPA,EU,EM
date,,,,,,,,,
2010-01-04,0.010229,0.014478,0.015916,0.000000,0.016018,0.000000,0.000000,0.016778,0.008399
2010-01-05,0.013898,0.024019,0.003111,-0.002722,0.004028,0.002535,0.002780,0.001316,0.008067
2010-01-06,0.007957,0.005706,0.000545,0.000409,0.001357,0.004635,0.006938,0.000586,0.005330
2010-01-07,0.007772,0.007498,0.003993,-0.002484,-0.000597,-0.004650,-0.003938,-0.000360,-0.006375
2010-01-08,-0.003189,0.000835,0.002878,0.003027,0.001356,0.010862,-0.002672,0.003554,0.001229
...,...,...,...,...,...,...,...,...,...
2011-02-16,0.008599,0.013400,0.006238,0.001925,0.007952,0.005717,0.018371,0.006975,0.003039
2011-02-17,0.009310,0.015977,0.003071,-0.001186,0.000345,0.002620,0.001686,-0.000581,0.001039
2011-02-18,0.000191,-0.001653,0.001923,0.002872,-0.000723,0.000568,0.005628,0.000572,0.006938
2011-02-21,-0.013069,-0.013706,-0.020742,-0.014239,-0.011275,0.001358,-0.011942,-0.012615,-0.000958
2011-02-22,-0.007246,-0.019442,0.000000,-0.000473,-0.002997,-0.017920,-0.012252,-0.005465,-0.014297

In [14]:
df['2010-01-04': '2010-02-06']

,ISE,ISE.1,SP,DAX,FTSE,NIKKEI,BOVESPA,EU,EM
date,,,,,,,,,
2010-01-04,0.010229,0.014478,0.015916,0.000000,0.016018,0.000000,0.000000,0.016778,0.008399
2010-01-05,0.013898,0.024019,0.003111,-0.002722,0.004028,0.002535,0.002780,0.001316,0.008067
2010-01-06,0.007957,0.005706,0.000545,0.000409,0.001357,0.004635,0.006938,0.000586,0.005330
2010-01-07,0.007772,0.007498,0.003993,-0.002484,-0.000597,-0.004650,-0.003938,-0.000360,-0.006375
2010-01-08,-0.003189,0.000835,0.002878,0.003027,0.001356,0.010862,-0.002672,0.003554,0.001229
2010-01-11,-0.016131,-0.006033,0.001745,0.000479,0.000704,0.007457,0.002417,-0.000498,0.005447
2010-01-12,-0.004549,-0.004339,-0.009425,-0.016273,-0.007140,0.000000,-0.005082,-0.009893,-0.003729
2010-01-13,0.017559,0.021362,0.008291,0.003383,-0.004593,-0.013335,0.004400,-0.000075,-0.007263
2010-01-14,0.002074,-0.002076,0.002424,0.004307,0.004503,0.015955,-0.008332,0.005500,0.002313
2010-01-15,-0.013517,-0.015516,-0.010882,-0.019033,-0.007815,0.006800,-0.011861,-0.011115,-0.002056
2010-01-18,0.010044,0.013495,0.012422,0.007220,0.007123,-0.011634,0.006114,0.005403,0.001725
2010-01-19,0.011098,0.007783,0.000000,0.009740,0.003398,-0.008342,0.007293,0.005296,0.002119
2010-01-20,0.005597,0.002294,-0.010654,-0.021129,-0.016884,-0.002547,-0.024750,-0.017593,-0.009051
2010-01-21,-0.003034,-0.013011,-0.019127,-0.018030,-0.015936,0.012116,-0.028707,-0.013777,-0.014856
2010-01-22,-0.023857,-0.027453,-0.022390,-0.009028,-0.006035,-0.025898,-0.000755,-0.008199,-0.012385
2010-01-25,0.005237,0.003952,0.004588,-0.011292,-0.008085,-0.007379,-0.010566,-0.007667,-0.004144
2010-01-26,0.000672,-0.008489,-0.004212,0.006648,0.003151,-0.017988,0.000000,0.003882,-0.017438
2010-01-27,-0.004548,0.000288,0.004868,-0.004549,-0.011320,-0.007115,-0.006953,-0.010127,-0.007275
2010-01-28,0.012852,0.012920,-0.011888,-0.018397,-0.013857,0.015698,0.007929,-0.012274,0.010577
2010-01-29,-0.002191,-0.000908,-0.009878,0.012281,0.008283,-0.020983,-0.002840,0.010073,-0.006315
2010-02-01,0.015892,0.015822,0.014165,0.008113,0.011288,0.000684,0.017731,0.008520,0.001817
2010-02-02,-0.006838,-0.003184,0.012890,0.009711,0.006818,0.016142,0.008838,0.009227,0.001154
2010-02-03,-0.001432,0.000667,-0.005489,-0.006602,-0.005733,0.003200,-0.000804,-0.005941,0.011541
2010-02-04,-0.029575,-0.040104,-0.031636,-0.024784,-0.021901,-0.004658,-0.048467,-0.027519,-0.019774
2010-02-05,-0.038301,-0.053827,0.002893,-0.018035,-0.015373,-0.029286,-0.018486,-0.021005,-0.027290

In [15]:
df[:'2010']

,ISE,ISE.1,SP,DAX,FTSE,NIKKEI,BOVESPA,EU,EM
date,,,,,,,,,
2009-01-05,0.035754,0.038376,-0.004679,0.002193,0.003894,0.000000,0.031190,0.012698,0.028524
2009-01-06,0.025426,0.031813,0.007787,0.008455,0.012866,0.004162,0.018920,0.011341,0.008773
2009-01-07,-0.028862,-0.026353,-0.030469,-0.017833,-0.028735,0.017293,-0.035899,-0.017073,-0.020015
2009-01-08,-0.062208,-0.084716,0.003391,-0.011726,-0.000466,-0.040061,0.028283,-0.005561,-0.019424
2009-01-09,0.009860,0.009658,-0.021533,-0.019873,-0.012710,-0.004474,-0.009764,-0.010989,-0.007802
...,...,...,...,...,...,...,...,...,...
2010-12-27,0.001346,0.000634,0.000000,0.000000,-0.002082,0.007444,0.000000,-0.005861,-0.002417
2010-12-28,0.001285,0.000438,0.000771,0.000197,0.000000,-0.006137,0.003504,0.000209,-0.000196
2010-12-29,0.004171,-0.005582,0.001009,0.003346,0.000000,0.005031,0.013300,0.001923,0.007861
2010-12-30,0.001535,0.008438,-0.001509,-0.011687,-0.004245,-0.011240,0.005106,-0.009191,0.003314
2010-12-31,-0.012312,-0.006861,-0.000191,0.000000,-0.011979,0.016404,0.009435,-0.006158,0.002789

In [16]:
df['2010-01': '2010-06']

,ISE,ISE.1,SP,DAX,FTSE,NIKKEI,BOVESPA,EU,EM
date,,,,,,,,,
2010-01-04,0.010229,0.014478,0.015916,0.000000,0.016018,0.000000,0.000000,0.016778,0.008399
2010-01-05,0.013898,0.024019,0.003111,-0.002722,0.004028,0.002535,0.002780,0.001316,0.008067
2010-01-06,0.007957,0.005706,0.000545,0.000409,0.001357,0.004635,0.006938,0.000586,0.005330
2010-01-07,0.007772,0.007498,0.003993,-0.002484,-0.000597,-0.004650,-0.003938,-0.000360,-0.006375
2010-01-08,-0.003189,0.000835,0.002878,0.003027,0.001356,0.010862,-0.002672,0.003554,0.001229
...,...,...,...,...,...,...,...,...,...
2010-06-24,0.000166,-0.008024,-0.016946,-0.014455,-0.015236,0.000467,-0.018948,-0.017801,-0.006717
2010-06-25,-0.000920,-0.003591,0.002855,-0.007366,-0.010585,-0.019411,0.013778,-0.007954,-0.002311
2010-06-28,0.010132,0.016951,-0.002036,0.014168,0.004981,-0.004481,-0.009283,0.009125,0.000540
2010-06-29,-0.021816,-0.028443,-0.031508,-0.033893,-0.031547,-0.012798,-0.035613,-0.034903,-0.021033
2010-06-30,-0.006830,-0.006195,-0.010164,0.002264,0.000549,-0.019842,-0.016955,0.002202,-0.006962

In [17]:
pd.date_range(start='2018-01-20', end='2018-01-23', freq='D').astype(str).tolist()

['2018-01-20', '2018-01-21', '2018-01-22', '2018-01-23']

In [18]:
pd.date_range(start='2018-01-20', periods=4, freq='D').astype(str).tolist()

['2018-01-20', '2018-01-21', '2018-01-22', '2018-01-23']

In [19]:
pd.date_range(start='2018-01-20', periods=4, freq='2D').astype(str).tolist()

['2018-01-20', '2018-01-22', '2018-01-24', '2018-01-26']

In [20]:
pd.date_range(start='2018-01-20',periods=4, freq='ME').astype(str).tolist()

['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30']

In [21]:
pd.date_range(start='2018-01-20', periods=4, freq='MS').astype(str).tolist()

['2018-02-01', '2018-03-01', '2018-04-01', '2018-05-01']

In [22]:
(pd.date_range(start='2018-01-20', end='2018-01-23', freq='D') + pd.Timedelta(4, unit='D')).astype(str).tolist()

['2018-01-24', '2018-01-25', '2018-01-26', '2018-01-27']

In [23]:
(pd.date_range(start='2018-01-20', end='2018-01-23', freq='D') + pd.Timedelta(4, unit='W')).astype(str).tolist()

['2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20']

## Resampling, Shifting, Rolling Window and Expanding Window Operations

In [24]:
m_df = df[['ISE']].resample('MS').mean()
display(m_df.head())

w_df = df[['ISE']].resample('W-MON').mean()
display(w_df.head())

                 ISE
date
2009-01-01 -0.002024
2009-02-01 -0.003820
2009-03-01  0.003175
2009-04-01  0.009799
2009-05-01  0.005297

                 ISE
date
2009-01-05  0.035754
2009-01-12 -0.016995
2009-01-19 -0.005143
2009-01-26  0.007167
2009-02-02 -0.005458

In [25]:
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df.index,
    y=df['ISE'],
    opacity=0.4,
    name='ISE',
    line={'dash': 'dot'}
))

fig.add_trace(go.Scatter(
    x=m_df.index,
    y=m_df['ISE'],
    opacity=1.0,
    name='ISE Monthly'
))

fig.add_trace(go.Scatter(
    x=w_df.index,
    y=w_df['ISE'],
    opacity=1.0,
    name='ISE Weekly',
    line={'dash': 'dash'}
))

fig.show()

#### Shift
##### Shifting a series along the temporal dimension is another valuable operation

In [26]:
plot_df = df.loc[:, ['ISE']]

# Shift forward by one day
plot_df['ISE_shift_1'] = df[['ISE']].shift(1)

# Shift backward by one day
plot_df['ISE_shift_-1'] = df[['ISE']].shift(-1).shift(-1)

plot_df = plot_df.dropna().iloc[20:40].reset_index()
plot_df = pd.melt(plot_df, id_vars='date')

fig = px.line(plot_df, x='date', y='value', color='variable', line_dash='variable', template='plotly_white')
fig.update_layout(
    yaxis_tickfont_size=15,
    xaxis_tickfont_size=15,
    legend_font_size=15
)

fig.show()

In [27]:
plot_df = df.loc[:, ['ISE']]

# Moving average of 5 days
plot_df['ISE_rolling_5_mean'] = df[['ISE']].rolling(window=5).mean()

plot_df = plot_df.dropna().iloc[20:50].reset_index()
plot_df = pd.melt(plot_df, id_vars='date')
fig = px.line(plot_df, x='date', y='value', color='variable', line_dash='variable', template='plotly_white')
fig.update_layout(
    yaxis_tickfont_size=15,
    xaxis_tickfont_size=15,
    legend_font_size=15
)

In [28]:
plot_df = df.loc[:, ['ISE']]

# Moving average of 30 days
plot_df['ISE_rolling_30_mean'] = df[['ISE']].rolling(window=120).mean()

# Expanding average
plot_df['ISE_expanding_mean'] = df[['ISE']].expanding().mean()

plot_df.drop(columns='ISE', inplace=True)
plot_df = plot_df.dropna().reset_index()
plot_df = pd.melt(plot_df, id_vars='date')

fig = px.line(plot_df, x='date', y='value', color='variable', line_dash='variable', template='plotly_white')
fig.update_layout(
    yaxis_tickfont_size=15,
    xaxis_tickfont_size=15,
    legend_font_size=15
)

fig.show()

## Missing Value Treatment

In [29]:
def format_plot(fig, legends, font_size=15, title_font_size=20):
    names = cycle(legends)
    fig.for_each_trace(lambda t: t.update(name=next(names)))
    fig.update_layout(
        autosize=False,
        width=900,
        height=500,
        title={
            'x': 0.5,
            'xanchor': 'center',
            'yanchor': 'top',
            'font': {
                'size': title_font_size
            }
        },
        legend={
            'title': {
                'text': '',
            },
            'font': {
                'size': font_size
            },
            'orientation': 'h',
            'yanchor': 'bottom',
            'y': 0.98,
            'xanchor': 'right',
            'x': 1
        },
        yaxis={
            'title': {
                'text': 'Value',
                'font': {
                    'size': font_size,
                },
            },
            'tickfont': {
                'size': font_size,
            },
        },
        xaxis={
            'title': {
                'text': 'Day',
                'font': {
                    'size': font_size,
                },
            },
            'tickfont': {
                'size': font_size,
            }

        }
    )

    return fig

In [30]:
df = pd.read_csv('../../notebooks/Chapter02/au_airquality.csv', sep=',')

df = df.loc[df['name'] == 'Monash', ['datetime', 'pm2_5_1_hr']]
df['datetime'] = pd.to_datetime(df['datetime'])
df.sort_values('datetime', inplace=True)
df.set_index('datetime', inplace=True)
df.head()

                     pm2_5_1_hr
datetime
2012-08-31 16:00:00         NaN
2013-03-18 16:00:00         NaN
2014-02-24 21:00:00         NaN
2014-04-24 16:00:00         NaN
2015-01-28 05:00:00         NaN

In [31]:
dates = df.index.unique().tolist()
null_dates = dates[-10:-7]

df.loc[null_dates, 'pm2_5_1_hr'] = np.nan

In [32]:
df = df.loc[dates[-15:-5], 'pm2_5_1_hr'].to_frame()

fig = px.line(df, x=df.index, y='pm2_5_1_hr', title='Missing Values in PM2.5')
fig = format_plot(fig, ['Original'])

fig.show()

In [33]:
_df = df.copy()

# Forward fill
_df['ffill'] = _df['pm2_5_1_hr'].ffill()

# Backward fill
_df['bfill'] = _df['pm2_5_1_hr'].bfill()

# Mean value fill
_df['mean_value'] = _df['pm2_5_1_hr'].fillna(df['pm2_5_1_hr'].mean())

In [34]:
# Plotting
plot_df = pd.melt(_df.reset_index(), id_vars='datetime', var_name='series')
fig = px.line(
    plot_df,
    x='datetime',
    y=['value'],
    line_dash='series',
    title='Forward, Backward, and Mean Value Fill'
)
fig = format_plot(
    fig,
    [
        'Original',
        'Forward Fill',
        'Backward Fill',
        'Mean Value Fill'
    ]
)
fig.show()

In [35]:
_df = df.copy()

_df['linear_interpolation'] = _df['pm2_5_1_hr'].interpolate(method='linear')
_df['nearest_interpolation'] = _df['pm2_5_1_hr'].interpolate(method='nearest')

In [36]:
_df

                     pm2_5_1_hr  linear_interpolation  nearest_interpolation
datetime
2024-03-20 12:00:00         0.8                 0.800                    0.8
2024-03-22 03:00:00         3.3                 3.300                    3.3
2024-03-22 08:00:00         4.7                 4.700                    4.7
2024-03-24 04:00:00         6.5                 6.500                    6.5
2024-03-26 09:00:00         7.6                 7.600                    7.6
2024-03-27 08:00:00         NaN                 7.825                    7.6
2024-03-27 15:00:00         NaN                 8.050                    7.6
2024-03-28 07:00:00         NaN                 8.275                    8.5
2024-03-29 11:00:00         8.5                 8.500                    8.5
2024-03-31 23:00:00        18.1                18.100                   18.1

In [37]:
# Plotting
plot_df = pd.melt(_df.reset_index(), id_vars='datetime', var_name='series')
plot_df

              datetime                 series   value
0  2024-03-20 12:00:00             pm2_5_1_hr   0.800
1  2024-03-22 03:00:00             pm2_5_1_hr   3.300
2  2024-03-22 08:00:00             pm2_5_1_hr   4.700
3  2024-03-24 04:00:00             pm2_5_1_hr   6.500
4  2024-03-26 09:00:00             pm2_5_1_hr   7.600
5  2024-03-27 08:00:00             pm2_5_1_hr     NaN
6  2024-03-27 15:00:00             pm2_5_1_hr     NaN
7  2024-03-28 07:00:00             pm2_5_1_hr     NaN
8  2024-03-29 11:00:00             pm2_5_1_hr   8.500
9  2024-03-31 23:00:00             pm2_5_1_hr  18.100
10 2024-03-20 12:00:00   linear_interpolation   0.800
11 2024-03-22 03:00:00   linear_interpolation   3.300
12 2024-03-22 08:00:00   linear_interpolation   4.700
13 2024-03-24 04:00:00   linear_interpolation   6.500
14 2024-03-26 09:00:00   linear_interpolation   7.600
15 2024-03-27 08:00:00   linear_interpolation   7.825
16 2024-03-27 15:00:00   linear_interpolation   8.050
17 2024-03-28 07:00:00   linear_interpolation   8.275
18 2024-03-29 11:00:00   linear_interpolation   8.500
19 2024-03-31 23:00:00   linear_interpolation  18.100
20 2024-03-20 12:00:00  nearest_interpolation   0.800
21 2024-03-22 03:00:00  nearest_interpolation   3.300
22 2024-03-22 08:00:00  nearest_interpolation   4.700
23 2024-03-24 04:00:00  nearest_interpolation   6.500
24 2024-03-26 09:00:00  nearest_interpolation   7.600
25 2024-03-27 08:00:00  nearest_interpolation   7.600
26 2024-03-27 15:00:00  nearest_interpolation   7.600
27 2024-03-28 07:00:00  nearest_interpolation   8.500
28 2024-03-29 11:00:00  nearest_interpolation   8.500
29 2024-03-31 23:00:00  nearest_interpolation  18.100

In [38]:
fig = px.line(plot_df, x='datetime', y=['value'], line_dash='series', title='Linear and Nearest Interpolation')

fig = format_plot(fig, ['Original', 'Linear Interpolation', 'Nearest Interpolation'])

fig.show()

In [39]:
_df = df.copy()
_df['spline_interpolation'] = _df['pm2_5_1_hr'].interpolate(methos='spline', order=2)
_df['polynomial_interpolation'] = _df['pm2_5_1_hr'].interpolate(method='polynomial', order=5)
_df

,pm2_5_1_hr,spline_interpolation,polynomial_interpolation
datetime,,,
2024-03-20 12:00:00,0.8,0.800,0.800000
2024-03-22 03:00:00,3.3,3.300,3.300000
2024-03-22 08:00:00,4.7,4.700,4.700000
2024-03-24 04:00:00,6.5,6.500,6.500000
2024-03-26 09:00:00,7.6,7.600,7.600000
2024-03-27 08:00:00,NaN,7.825,10.380424
2024-03-27 15:00:00,NaN,8.050,10.994214
2024-03-28 07:00:00,NaN,8.275,11.458565
2024-03-29 11:00:00,8.5,8.500,8.500000
2024-03-31 23:00:00,18.1,18.100,18.100000

In [40]:
plot_df = pd.melt(_df.reset_index(), id_vars='datetime', var_name='series')
plot_df

              datetime                    series      value
0  2024-03-20 12:00:00                pm2_5_1_hr   0.800000
1  2024-03-22 03:00:00                pm2_5_1_hr   3.300000
2  2024-03-22 08:00:00                pm2_5_1_hr   4.700000
3  2024-03-24 04:00:00                pm2_5_1_hr   6.500000
4  2024-03-26 09:00:00                pm2_5_1_hr   7.600000
5  2024-03-27 08:00:00                pm2_5_1_hr        NaN
6  2024-03-27 15:00:00                pm2_5_1_hr        NaN
7  2024-03-28 07:00:00                pm2_5_1_hr        NaN
8  2024-03-29 11:00:00                pm2_5_1_hr   8.500000
9  2024-03-31 23:00:00                pm2_5_1_hr  18.100000
10 2024-03-20 12:00:00      spline_interpolation   0.800000
11 2024-03-22 03:00:00      spline_interpolation   3.300000
12 2024-03-22 08:00:00      spline_interpolation   4.700000
13 2024-03-24 04:00:00      spline_interpolation   6.500000
14 2024-03-26 09:00:00      spline_interpolation   7.600000
15 2024-03-27 08:00:00      spline_interpolation   7.825000
16 2024-03-27 15:00:00      spline_interpolation   8.050000
17 2024-03-28 07:00:00      spline_interpolation   8.275000
18 2024-03-29 11:00:00      spline_interpolation   8.500000
19 2024-03-31 23:00:00      spline_interpolation  18.100000
20 2024-03-20 12:00:00  polynomial_interpolation   0.800000
21 2024-03-22 03:00:00  polynomial_interpolation   3.300000
22 2024-03-22 08:00:00  polynomial_interpolation   4.700000
23 2024-03-24 04:00:00  polynomial_interpolation   6.500000
24 2024-03-26 09:00:00  polynomial_interpolation   7.600000
25 2024-03-27 08:00:00  polynomial_interpolation  10.380424
26 2024-03-27 15:00:00  polynomial_interpolation  10.994214
27 2024-03-28 07:00:00  polynomial_interpolation  11.458565
28 2024-03-29 11:00:00  polynomial_interpolation   8.500000
29 2024-03-31 23:00:00  polynomial_interpolation  18.100000

In [41]:
fig = px.line(plot_df, x='datetime', y=['value'], line_dash='series', title='Spline and Polynomial Interpolation')
fig = format_plot(fig, ['Original', 'Spline Interpolation', 'Polynomial Interpolation'])

fig.show()