In [1]:
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import os
import plotly.io as pio
import pandas as pd
from pathlib import Path
from tqdm.auto import tqdm

pio.templates.default = 'plotly_white'
np.random.seed()
tqdm.pandas()

from IPython.display import display

In [2]:
os.makedirs('imgs/chapter_02', exist_ok=True)
source_data = Path('../../data/london_smart_meters/')
block_data_path = source_data/'hhblock_dataset'/'hhblock_dataset'

In [3]:
assert block_data_path.is_dir()

### Converting half hourly block level dataset into a time series data

In [4]:
block_1 = pd.read_csv(block_data_path/'block_0.csv', parse_dates=False)
block_1.head()

,LCLid,day,hh_0,hh_1,hh_2,hh_3,hh_4,hh_5,hh_6,hh_7,...,hh_38,hh_39,hh_40,hh_41,hh_42,hh_43,hh_44,hh_45,hh_46,hh_47
0,MAC000002,2012-10-13,0.263,0.269,0.275,0.256,0.211,0.136,0.161,0.119,...,0.918,0.278,0.267,0.239,0.230,0.233,0.235,0.188,0.259,0.250
1,MAC000002,2012-10-14,0.262,0.166,0.226,0.088,0.126,0.082,0.123,0.083,...,1.075,0.956,0.821,0.745,0.712,0.511,0.231,0.210,0.278,0.159
2,MAC000002,2012-10-15,0.192,0.097,0.141,0.083,0.132,0.070,0.130,0.074,...,1.164,0.249,0.225,0.258,0.260,0.334,0.299,0.236,0.241,0.237
3,MAC000002,2012-10-16,0.237,0.237,0.193,0.118,0.098,0.107,0.094,0.109,...,0.966,0.172,0.192,0.228,0.203,0.211,0.188,0.213,0.157,0.202
4,MAC000002,2012-10-17,0.157,0.211,0.155,0.169,0.101,0.117,0.084,0.118,...,0.223,0.075,0.230,0.208,0.265,0.377,0.327,0.277,0.288,0.256

In [5]:
block_1['day'] = pd.to_datetime(block_1['day'], yearfirst=True)
block_1.head()

,LCLid,day,hh_0,hh_1,hh_2,hh_3,hh_4,hh_5,hh_6,hh_7,...,hh_38,hh_39,hh_40,hh_41,hh_42,hh_43,hh_44,hh_45,hh_46,hh_47
0,MAC000002,2012-10-13,0.263,0.269,0.275,0.256,0.211,0.136,0.161,0.119,...,0.918,0.278,0.267,0.239,0.230,0.233,0.235,0.188,0.259,0.250
1,MAC000002,2012-10-14,0.262,0.166,0.226,0.088,0.126,0.082,0.123,0.083,...,1.075,0.956,0.821,0.745,0.712,0.511,0.231,0.210,0.278,0.159
2,MAC000002,2012-10-15,0.192,0.097,0.141,0.083,0.132,0.070,0.130,0.074,...,1.164,0.249,0.225,0.258,0.260,0.334,0.299,0.236,0.241,0.237
3,MAC000002,2012-10-16,0.237,0.237,0.193,0.118,0.098,0.107,0.094,0.109,...,0.966,0.172,0.192,0.228,0.203,0.211,0.188,0.213,0.157,0.202
4,MAC000002,2012-10-17,0.157,0.211,0.155,0.169,0.101,0.117,0.084,0.118,...,0.223,0.075,0.230,0.208,0.265,0.377,0.327,0.277,0.288,0.256

In [6]:
block_1.groupby('LCLid')['day'].max().sample(5)

LCLid
MAC003423   2014-02-27
MAC003775   2014-01-12
MAC003863   2014-02-27
MAC003597   2014-02-27
MAC004034   2013-09-18
Name: day, dtype: datetime64[ns]

In [7]:
max_date = None

for f in tqdm(block_data_path.glob('*.csv')):
    df = pd.read_csv(f, parse_dates=False)
    df['day'] = pd.to_datetime(df['day'], yearfirst=True)
    if max_date is None:
        max_date = df['day'].max()
    else:
        if df['day'].max() > max_date:
            max_date = df['day'].max()

print(f"Max date across all blocks: {max_date}")
del df

0it [00:00, ?it/s]

Max date across all blocks: 2014-02-27 00:00:00

In [8]:
block_1.head()

,LCLid,day,hh_0,hh_1,hh_2,hh_3,hh_4,hh_5,hh_6,hh_7,...,hh_38,hh_39,hh_40,hh_41,hh_42,hh_43,hh_44,hh_45,hh_46,hh_47
0,MAC000002,2012-10-13,0.263,0.269,0.275,0.256,0.211,0.136,0.161,0.119,...,0.918,0.278,0.267,0.239,0.230,0.233,0.235,0.188,0.259,0.250
1,MAC000002,2012-10-14,0.262,0.166,0.226,0.088,0.126,0.082,0.123,0.083,...,1.075,0.956,0.821,0.745,0.712,0.511,0.231,0.210,0.278,0.159
2,MAC000002,2012-10-15,0.192,0.097,0.141,0.083,0.132,0.070,0.130,0.074,...,1.164,0.249,0.225,0.258,0.260,0.334,0.299,0.236,0.241,0.237
3,MAC000002,2012-10-16,0.237,0.237,0.193,0.118,0.098,0.107,0.094,0.109,...,0.966,0.172,0.192,0.228,0.203,0.211,0.188,0.213,0.157,0.202
4,MAC000002,2012-10-17,0.157,0.211,0.155,0.169,0.101,0.117,0.084,0.118,...,0.223,0.075,0.230,0.208,0.265,0.377,0.327,0.277,0.288,0.256

In [9]:
# Reshape the dataframe into the long form with hour blocks along the rows
block_1 = block_1.set_index(['LCLid', 'day']).stack().reset_index().rename(columns={'level_2': 'hour_block', 0: 'energy_consumption'})

# Creating a numerical hour block column
block_1['offset'] = block_1['hour_block'].str.replace('hh_', '').astype(int)

block_1.head()

       LCLid        day hour_block  energy_consumption  offset
0  MAC000002 2012-10-13       hh_0               0.263       0
1  MAC000002 2012-10-13       hh_1               0.269       1
2  MAC000002 2012-10-13       hh_2               0.275       2
3  MAC000002 2012-10-13       hh_3               0.256       3
4  MAC000002 2012-10-13       hh_4               0.211       4

### Compact Form

In [10]:
def preprocess_compact(x):
    start_date = x['day'].min()
    name = x['LCLid'].unique()[0]

    # Fill missing dates with NaN
    # Create a date range from min to max
    dr = pd.date_range(start=x['day'].min(), end=max_date, freq='1D')

    # Add hh_0 to hh_47 to columns
    dr = pd.DataFrame(columns=[f'hh_{i}' for i in range(48)], index=dr).unstack().reset_index()

    #Rename columns
    dr.columns = ['hour_block', 'day', '_']

    # Left merging the dataframes
    dr = dr.merge(x, on=['hour_block', 'day'], how='left')

    # Sort rows
    dr.sort_values(['day', 'offset'], inplace=True)

    # Extract time series array
    ts = dr['energy_consumption'].values
    len_ts = len(ts)

    return start_date, name, ts, len_ts

In [11]:
def load_process_block_compact(block_df, freq='30min', ts_identifier='series_name', value_name='series_value'):

    grps = block_df.groupby('LCLid')
    all_series = []
    all_start_dates = []
    all_names = []
    all_data = {}
    all_len = []

    for idx, df in tqdm(grps, leave=False):
        start_date, name, ts, len_ts = preprocess_compact(df)
        all_series.append(ts)
        all_start_dates.append(start_date)
        all_names.append(name)
        all_len.append(len_ts)

    all_data[ts_identifier] = all_names
    all_data['start_timestamp'] = all_start_dates
    all_data['frequency'] = freq
    all_data[value_name] = all_series
    all_data['series_length'] = all_len

    return pd.DataFrame(all_data)

In [12]:
block1_compact = load_process_block_compact(block_1, freq='30min', ts_identifier='LCLid', value_name='energy_consumption')

  0%|          | 0/50 [00:00<?, ?it/s]

In [13]:
block1_compact.head()

,LCLid,start_timestamp,frequency,energy_consumption,series_length
0,MAC000002,2012-10-13,30min,"[0.263, 0.2689999999999999, 0.275, 0.256, 0.21...",24144
1,MAC000246,2011-12-04,30min,"[0.175, 0.098, 0.144, 0.065, 0.071, 0.037, 0.0...",39216
2,MAC000450,2012-03-23,30min,"[1.337, 1.426, 0.996, 0.971, 0.994, 0.952, 0.8...",33936
3,MAC001074,2012-05-09,30min,"[0.18, 0.086, 0.106, 0.173, 0.146, 0.223, 0.21...",31680
4,MAC003223,2012-09-18,30min,"[0.076, 0.079, 0.123, 0.109, 0.051, 0.069, 0.0...",25344

In [14]:
display(block1_compact.memory_usage(deep=True))

Index                  132
LCLid                 2900
start_timestamp        400
frequency             2700
energy_consumption    6000
series_length          400
dtype: int64

In [15]:
def preprocess_expanded(x):
    start_date = x['day'].min()

    # Create a date range from min to max
    dr = pd.date_range(start=x['day'].min(), end=x['day'].max(), freq='1D')

    # Add hh_0 to hh_47 to columns
    dr = pd.DataFrame(columns=[f'hh_{i}' for i in range(48)], index=dr).unstack().reset_index()

    # Rename columns
    dr.columns = ['hour_block', 'day', '_']

    # Merge dataframes
    dr = dr.merge(x, on=['hour_block', 'day'], how='left')
    dr['series_length'] = len(dr)

    return dr

In [16]:
def load_process_block_expanded(block_df, freq='30min'):
    grps = block_df.groupby('LCLid')
    all_series = []
    for idx, df in tqdm(grps, leave=False):
        ts = preprocess_expanded(df)
        all_series.append(ts)

    block_df = pd.concat(all_series)
    # Recreate offset because there would be null rows now
    block_df['offset'] = block_df['hour_block'].str.replace('hh_', '').astype(int)
    # Creating a datetime column with the date
    block_df['timestamp'] = block_df['day'] + block_df['offset']*30*pd.offsets.Minute()
    block_df['frequency'] = freq
    block_df.sort_values(['LCLid', 'timestamp'], inplace=True)
    block_df.drop(columns=['_', 'hour_block', 'offset', 'day'], inplace=True)
    return block_df

In [17]:
block1_expanded = load_process_block_expanded(block_1, freq='30min')

  0%|          | 0/50 [00:00<?, ?it/s]

/var/folders/bx/wnj_y5195_xdzx3fb1h_84180000gn/T/ipykernel_6356/1594791965.py:12: PerformanceWarning: Adding/subtracting object-dtype array to DatetimeArray not vectorized.
  block_df['timestamp'] = block_df['day'] + block_df['offset']*30*pd.offsets.Minute()

In [18]:
block1_expanded.head()

,LCLid,energy_consumption,series_length,timestamp,frequency
0,MAC000002,0.263,24144,2012-10-13 00:00:00,30min
503,MAC000002,0.269,24144,2012-10-13 00:30:00,30min
1006,MAC000002,0.275,24144,2012-10-13 01:00:00,30min
1509,MAC000002,0.256,24144,2012-10-13 01:30:00,30min
2012,MAC000002,0.211,24144,2012-10-13 02:00:00,30min

In [19]:
# We will use compact form. Delete example dataframes
del block1_expanded, block_1, block1_compact

### Reading and combining all the block data into a single dataframe

In [20]:
block_df_l = []

for file in tqdm(sorted(list(block_data_path.glob('*.csv'))), desc='Processing Blocks...'):
    block_df = pd.read_csv(file, parse_dates=False)
    block_df['day'] = pd.to_datetime(block_df['day'], yearfirst=True)
    # Taking only from 2012-01-01
    block_df = block_df.loc[block_df['day'] >= '2012-01-01']
    # Reshape the dataframe into the long form with the hour blocks along the rows
    block_df = block_df.set_index(['LCLid', 'day']).stack().reset_index().rename(columns={'level_2': 'hour_block', 0: 'energy_consumption'})
    # Create a numerical hourblock column
    block_df['offset'] = block_df['hour_block'].str.replace('hh_', '').astype(int)
    block_df_l.append(load_process_block_compact(block_df, freq='30min', ts_identifier='LCLid', value_name='energy_consumption'))

Processing Blocks...:   0%|          | 0/112 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/48 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/16 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/49 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/49 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/49 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/49 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

  0%|          | 0/50 [00:00<?, ?it/s]

In [21]:
hhblock_df = pd.concat(block_df_l)
del block_df_l
display(hhblock_df.memory_usage(deep=True))

Index                  44480
LCLid                 322480
start_timestamp        44480
frequency             300240
energy_consumption    667200
series_length          44480
dtype: int64

In [22]:
hhblock_df.head()

,LCLid,start_timestamp,frequency,energy_consumption,series_length
0,MAC000002,2012-10-13,30min,"[0.263, 0.2689999999999999, 0.275, 0.256, 0.21...",24144
1,MAC000246,2012-01-01,30min,"[0.509, 0.317, 0.253, 0.249, 0.93, 0.607, 0.10...",37872
2,MAC000450,2012-03-23,30min,"[1.337, 1.426, 0.996, 0.971, 0.994, 0.952, 0.8...",33936
3,MAC001074,2012-05-09,30min,"[0.18, 0.086, 0.106, 0.173, 0.146, 0.223, 0.21...",31680
4,MAC003223,2012-09-18,30min,"[0.076, 0.079, 0.123, 0.109, 0.051, 0.069, 0.0...",25344

## Merging additional information

#### Household info

In [23]:
# Household info
household_info = pd.read_csv(source_data/'informations_households.csv')
household_info.head()

       LCLid stdorToU    Acorn Acorn_grouped     file
0  MAC005492      ToU   ACORN-        ACORN-  block_0
1  MAC001074      ToU   ACORN-        ACORN-  block_0
2  MAC000002      Std  ACORN-A      Affluent  block_0
3  MAC003613      Std  ACORN-A      Affluent  block_0
4  MAC003597      Std  ACORN-A      Affluent  block_0

In [25]:
hhblock_df = hhblock_df.merge(household_info, on='LCLid', validate='one_to_one')
hhblock_df.head()

,LCLid,start_timestamp,frequency,energy_consumption,series_length,stdorToU,Acorn,Acorn_grouped,file
0,MAC000002,2012-10-13,30min,"[0.263, 0.2689999999999999, 0.275, 0.256, 0.21...",24144,Std,ACORN-A,Affluent,block_0
1,MAC000246,2012-01-01,30min,"[0.509, 0.317, 0.253, 0.249, 0.93, 0.607, 0.10...",37872,Std,ACORN-A,Affluent,block_0
2,MAC000450,2012-03-23,30min,"[1.337, 1.426, 0.996, 0.971, 0.994, 0.952, 0.8...",33936,Std,ACORN-A,Affluent,block_0
3,MAC001074,2012-05-09,30min,"[0.18, 0.086, 0.106, 0.173, 0.146, 0.223, 0.21...",31680,ToU,ACORN-,ACORN-,block_0
4,MAC003223,2012-09-18,30min,"[0.076, 0.079, 0.123, 0.109, 0.051, 0.069, 0.0...",25344,Std,ACORN-A,Affluent,block_0

#### Weather and Bank Holidays

In [26]:
bank_holidays = pd.read_csv(source_data/'uk_bank_holidays.csv', parse_dates=False)
bank_holidays['Bank holidays'] = pd.to_datetime(bank_holidays['Bank holidays'], yearfirst=True)
bank_holidays.set_index('Bank holidays', inplace=True)
bank_holidays.head()

                                                       Type
Bank holidays
2012-12-26                                       Boxing Day
2012-12-25                                    Christmas Day
2012-08-27                              Summer bank holiday
2012-05-06     Queen?s Diamond Jubilee (extra bank holiday)
2012-04-06             Spring bank holiday (substitute day)

In [27]:
weather_hourly = pd.read_csv(source_data/'weather_hourly_darksky.csv', parse_dates=False)
weather_hourly['time'] = pd.to_datetime(weather_hourly['time'], yearfirst=True)
weather_hourly.set_index('time', inplace=True)
weather_hourly.head()

,visibility,windBearing,temperature,dewPoint,pressure,apparentTemperature,windSpeed,precipType,icon,humidity,summary
time,,,,,,,,,,,
2011-11-11 00:00:00,5.97,104,10.24,8.86,1016.76,10.24,2.77,rain,partly-cloudy-night,0.91,Partly Cloudy
2011-11-11 01:00:00,4.88,99,9.76,8.83,1016.63,8.24,2.95,rain,partly-cloudy-night,0.94,Partly Cloudy
2011-11-11 02:00:00,3.70,98,9.46,8.79,1016.36,7.76,3.17,rain,partly-cloudy-night,0.96,Partly Cloudy
2011-11-11 03:00:00,3.12,99,9.23,8.63,1016.28,7.44,3.25,rain,fog,0.96,Foggy
2011-11-11 04:00:00,1.85,111,9.26,9.21,1015.98,7.24,3.70,rain,fog,1.00,Foggy

In [28]:
# Resamping at 30min and forward fill
weather_hourly = weather_hourly.resample('30min').ffill()
weather_hourly.head()

,visibility,windBearing,temperature,dewPoint,pressure,apparentTemperature,windSpeed,precipType,icon,humidity,summary
time,,,,,,,,,,,
2011-11-01 00:00:00,13.63,160,13.49,11.48,1008.14,13.49,3.11,rain,clear-night,0.88,Clear
2011-11-01 00:30:00,13.63,160,13.49,11.48,1008.14,13.49,3.11,rain,clear-night,0.88,Clear
2011-11-01 01:00:00,13.26,154,12.73,11.58,1007.88,12.73,3.08,rain,partly-cloudy-night,0.93,Partly Cloudy
2011-11-01 01:30:00,13.26,154,12.73,11.58,1007.88,12.73,3.08,rain,partly-cloudy-night,0.93,Partly Cloudy
2011-11-01 02:00:00,12.94,161,13.65,12.14,1007.09,13.65,3.71,rain,clear-night,0.91,Clear

In [29]:
def map_weather_holidays(row):
    date_range = pd.date_range(row['start_timestamp'], period=row['series_length'], freq=row['frequency'])
    std_df = pd.DataFrame(index=date_range)
    # Filling Na with NO_HOLIDAY cause rows before earliers holiday will be NaN
    holidays = std_df.join(bank_holidays, how='left').fillna('NO_HOLIDAY')
    weather = std_df.join(weather_hourly, how='left')

    assert len(holidays) == row['series_length']
    assert len(weather) == row['series_length']

    row['holidays'] = holidays['Type'].values
    for col in weather:
        row[col] = weather[col].values

    return row

In [30]:
hhblock_df = hhblock_df.progress_apply(map_weather_holidays, axis=1)
hhblock_df.head()

  0%|          | 0/5560 [00:00<?, ?it/s]

TypeError: DatetimeArray._generate_range() got an unexpected keyword argument 'period'. Did you mean 'periods'?